### ISSUE TITLE
Spock fails its test suite

### ISSUE THREAD

**Issue by mdorman** [agrafix/Spock#44] opened 2015-08-25 08:56 UTC
When building with the NixOS automated builder, we see failures like:

```
  test/Web/Spock/FrameworkSpecHelper.hs:108:
  1) Web.Spock.Safe.SafeRouting.Headers supports custom headers
       uncaught exception: ErrorCall (toEnum{MultiHeader}: tag (-12565) is outside of enumeration's range (0,12))

  test/Web/Spock/FrameworkSpecHelper.hs:116:
  2) Web.Spock.Safe.SafeRouting.Headers supports multi headers
       uncaught exception: ErrorCall (toEnum{MultiHeader}: tag (-12565) is outside of enumeration's range (0,12))

  test/Web/Spock/FrameworkSpecHelper.hs:108:
  3) Web.Spock.Simple.SimpleRouting.Headers supports custom headers
       uncaught exception: ErrorCall (toEnum{MultiHeader}: tag (-12565) is outside of enumeration's range (0,12))

  test/Web/Spock/FrameworkSpecHelper.hs:116:
  4) Web.Spock.Simple.SimpleRouting.Headers supports multi headers
       uncaught exception: ErrorCall (toEnum{MultiHeader}: tag (-12565) is outside of enumeration's range (0,12))
```

You can also [check the full build log](http://hydra.cryp.to/build/1112170/nixlog/2/raw).

**Comment by agrafix** [comment] 2015-08-25 10:44
Thank you for the report! I've filed a [GHC bug](https://ghc.haskell.org/trac/ghc/ticket/10792) because it only happens on some infrastructures and I can not trace down the bug in Spock code. I will provide a hacky quick fix for now.

**Comment by agrafix** [comment] 2015-08-25 16:21
@mdorman what infrastructure does the NixOS automated builder run on? E.g. what x64 or x86, what exact linux distribution, etc?

**Comment by mdorman** [comment] 2015-08-25 16:41
Well, the linux distribution is nixos. :)  The builder is x86_64.

**Comment by agrafix** [comment] 2015-08-25 17:00
How can I reproduce this? I've tried with the reproduce script ( `bash <(curl http://hydra.cryp.to/build/1112170/reproduce)` ), but that crashes with `fatal: reference is not a tree: 9b516e5979c1cd4787306a6cb0c79a8296c9201e` @mdorman

**Comment by agrafix** [comment] 2015-08-25 18:32
New Spock version *might* fix this...

**Comment by mdorman** [comment] 2015-08-25 18:50
@agrafix I'm sorry I didn't get back to you more quickly.  I'll give the fix a shot.

I'm sorry I don't have a good suggestion for how best to reproduce.  Perhaps @peti, who actually runs the buildhost might have some suggestions---I just try and triage failures, but my knowledge of Nix is still sometimes awfully superficial.

**Comment by peti** [comment] 2015-08-25 19:11
@agrafix, I don't think there's an easy way to re-produce this exact same build without running NixOS (say, in a container or VM). If you do run NixOS, then these builds are quite trivial to re-produce, but without the Nix infrastructure it's not so simple.

**Comment by agrafix** [comment] 2015-08-26 08:23
@peti I did setup nixos on a vm and then tried the script above resulting in the provided error...

@mdorman Thanks!

**Comment by peti** [comment] 2015-08-26 08:41
@agrafix, if you have NixOS available, then the proper way to re-produce the build is this:

    cd /tmp
    git clone --branch=haskell-updates https://github.com/peti/nixpkgs.git
    nix-build /tmp/nixpkgs -A haskellPackages.Spock

Note, however, that the test suite failure is transient on NixOS, too. I ran the build manually, and it succeeds fine in 9 out of 10 cases. Whatever causes the test suite to fail, it's most likely sensitive to timing.

**Comment by agrafix** [comment] 2015-08-27 16:19
@peti Thanks for the input, that's "bad" news... :-(

@mdorman Does the new version compile again?

**Comment by peti** [comment] 2015-08-27 17:29
Version 0.9.0.1 did not produce that error yet: http://hydra.cryp.to/job/nixpkgs/haskell-updates/haskellPackages.Spock.x86_64-linux. Not sure what that means.

**Comment by agrafix** [comment] 2015-08-27 19:50
Hopefully that fixes the bug for now, but I'll still need to investigate the origin...

**Comment by agrafix** [comment] 2015-09-08 10:29
Looks like 0.9.0.1 is fine for now. Closing this

**Closed by agrafix** 2015-09-08 10:29 UTC
